// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error)
}

var _ Querier = (*Queries)(nil)
