// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlc

import (
	"context"
	"time"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, created_by)
VALUES ($1, $2)
RETURNING id, name, created_by, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name      string `json:"name"`
	CreatedBy int64  `json:"created_by"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.CreatedBy)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, user_id, role, created_at
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	UserID      int64  `json:"user_id"`
	Role        string `json:"role"`
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, createWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :execrows
DELETE FROM workspace_members
WHERE workspace_id = $1
  AND id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	ID          int64 `json:"id"`
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceForUser = `-- name: GetWorkspaceForUser :one
SELECT
    w.id,
    w.name,
    wm.role,
    w.created_at,
    w.updated_at
FROM workspace_members wm
JOIN workspaces w ON w.id = wm.workspace_id
WHERE wm.user_id = $1
  AND w.id = $2
`

type GetWorkspaceForUserParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

type GetWorkspaceForUserRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetWorkspaceForUser(ctx context.Context, arg GetWorkspaceForUserParams) (GetWorkspaceForUserRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForUser, arg.UserID, arg.ID)
	var i GetWorkspaceForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT
    wm.id,
    wm.workspace_id,
    wm.user_id,
    u.email AS user_email,
    u.name AS user_name,
    wm.role,
    wm.created_at
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = $1
  AND wm.id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	ID          int64 `json:"id"`
}

type GetWorkspaceMemberRow struct {
	ID          int64     `json:"id"`
	WorkspaceID int64     `json:"workspace_id"`
	UserID      int64     `json:"user_id"`
	UserEmail   string    `json:"user_email"`
	UserName    string    `json:"user_name"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.ID)
	var i GetWorkspaceMemberRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT
    wm.id,
    wm.workspace_id,
    wm.user_id,
    u.email AS user_email,
    u.name AS user_name,
    wm.role,
    wm.created_at
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = $1
ORDER BY wm.id ASC
`

type ListWorkspaceMembersRow struct {
	ID          int64     `json:"id"`
	WorkspaceID int64     `json:"workspace_id"`
	UserID      int64     `json:"user_id"`
	UserEmail   string    `json:"user_email"`
	UserName    string    `json:"user_name"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID int64) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceMembersRow
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.UserEmail,
			&i.UserName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT
    w.id,
    w.name,
    wm.role,
    w.created_at,
    w.updated_at
FROM workspace_members wm
JOIN workspaces w ON w.id = wm.workspace_id
WHERE wm.user_id = $1
ORDER BY w.id DESC
`

type ListWorkspacesForUserRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID int64) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacesForUserRow
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :one
UPDATE workspace_members wm
SET role = $3
FROM users u
WHERE u.id = wm.user_id
  AND wm.workspace_id = $1
  AND wm.id = $2
RETURNING
    wm.id,
    wm.workspace_id,
    wm.user_id,
    u.email AS user_email,
    u.name AS user_name,
    wm.role,
    wm.created_at
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	ID          int64  `json:"id"`
	Role        string `json:"role"`
}

type UpdateWorkspaceMemberRoleRow struct {
	ID          int64     `json:"id"`
	WorkspaceID int64     `json:"workspace_id"`
	UserID      int64     `json:"user_id"`
	UserEmail   string    `json:"user_email"`
	UserName    string    `json:"user_name"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (UpdateWorkspaceMemberRoleRow, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.ID, arg.Role)
	var i UpdateWorkspaceMemberRoleRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
